
server:
  port: 9080
  ssl:
    key-alias: selfsigned_ij_storage_sslserver
    key-password: changeit
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS


spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource: #uncomment this for db migration
    initialization-mode: always
    continue-on-error: true
    url: jdbc:mysql://localhost:3306/ijstorage?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true #Only for testing purposes we should implement ssl certificate
    username: ijstorageuser
    password: ijstoragepass
  application:
    name: storage-service
  profiles:
    active: prod
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN

